[package]
name = "echodb"
publish = true
edition = "2021"
version = "0.0.0"
readme = "README.md"
authors = ["Tobie Morgan Hitchcock <tobie@surrealdb.com>"]
description = "An embedded, in-memory, immutable, copy-on-write database engine"
repository = "https://github.com/surrealdb/echodb"
homepage = "https://github.com/surrealdb/echodb"
license = "Apache-2.0"
keywords = ["database", "embedded-database", "key-value", "kv store"]
categories = ["database-implementations", "data-structures", "embedded"]

[dependencies]
futures = "0.3.19"
im = "15.0.0"
thiserror = "1.0.30"
